# Generated by Django 3.0.3 on 2020-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bus', models.IntegerField()),
                ('cars', models.IntegerField()),
                ('truck', models.IntegerField()),
            ],
        ),
    ]
